#ifndef EXIT_CODES_H
#define EXIT_CODES_H 1

/* Exit codes used by the DAQ software. */

/* general exit codes: 0-9 */
#define EXIT_CLEAN             0;  /*!< Clean exit. */
#define EXIT_UNSPECIFIED_ERROR 1;  /*!< Unclean exit with an otherwise unspecified error.  More information might be generated by a STDOUT dump or logfile write immediately preceding this exit. */

/* exit codes specific to the minervadaq program */
#define EXIT_CLEAN_SENTINEL   2;	/*!< Clean exit.  Sentinel frame is coming from this node. */
#define EXIT_CLEAN_NOSENTINEL 3;  /*!< Clean exit.  NO sentinel is coming from this node. */

/* miscellaneous exit codes: 10-19 */
#define EXIT_CONFIG_ERROR    10;
#define EXIT_ETSTARTUP_ERROR 11; /*!< Couldn't start up the ET machinery or connect to the ET system. */

/* CAEN-related errors: 20-29 */
#define EXIT_CAEN_CONTROLLER_ERROR  20;
#define EXIT_CAEN_INTERRUPT_FAILURE 21;

/* CRIM errors: 30-39 */
#define EXIT_CRIM_UNSPECIFIED_ERROR 30;
#define EXIT_CRIM_INTERRUPT_ERROR   31;
#define EXIT_CRIM_IRQTIMEOUT_ERROR  32;

/* CROC errors: 40-49 */
#define EXIT_CROC_UNSPECIFIED_ERROR 40;
#define EXIT_CROC_WRITE_ERROR       41;
#define EXIT_CROC_CRC_ERROR         42;
#define EXIT_CROC_TIMEOUT_ERROR     43;
#define EXIT_CROC_FIFOEMPTY_ERROR   44;
#define EXIT_CROC_FIFOFULL_ERROR    45;
#define EXIT_CROC_DPMFULL_ERROR     46;

/* FEB errors: 50-59 */
#define EXIT_FEB_UNSPECIFIED_ERROR 50;
#define EXIT_FEB_NHITS_ERROR       51;

/* DAQ software errors: 60-69 */
#define EXIT_DAQ_TRIGGER_ERROR 60;

#endif
