#
# etObject-specific Makefile options
#

ifndef ETOBJECT_INSTALL
  ETOBJECT_INSTALL = $(INSTALL_DIR)
endif

CFLAGS    += -I$(ETOBJECT_INSTALL)/include
CXXFLAGS  += -I$(ETOBJECT_INSTALL)/include

MISC_LIBS += -L$(ETOBJECT_INSTALL)/$(BMS_OSNAME)/lib -letObject
