#
# evio Makefile options
#

ifndef EVIO_INSTALL
  EVIO_INSTALL = $(INSTALL_DIR)
endif

CFLAGS   += -I$(EVIO_INSTALL)/include
CXXFLAGS += -I$(EVIO_INSTALL)/include

MISC_LIBS += -L$(EVIO_INSTALL)/$(BMS_OSNAME)/lib -levioxx -levio
