#!/bin/bash

# Argument List:
#  $1 == et_system file name (should include full path)
#  $2 == number of gates to process
#  $3 == port mod
if [ $# -ne 3 ]; then
  echo "Please supply et_system file name, number of gates, and port (1201-1250)."
  exit 1
fi

ETSYS=$1
EVENTS=$2
PORT=$3
EVENT_SIZE=49152 # 48 kB (was two kilobytes) - this is the *ET event* size (glob size)

if [ "$LOCALE" == "" ]
then
  echo No LOCALE defined!  It is impossible to configure the MINERvA DAQ Environment!
  exit 1
fi

if [ "$ET_HOME" == "" ]
then
  echo No ET_HOME defined!  Please configure your environment!
  exit 1
fi

# The ETSYS should include the full path.
echo ETSYSTEM ETSYS      = $ETSYS
echo ETSYSTEM EVENTS     = $EVENTS
echo ETSYSTEM EVENT_SIZE = $EVENT_SIZE
echo ETSYSTEM PORT       = $PORT
$ET_HOME/bin/et_start -v -f $ETSYS -n $EVENTS -s $EVENT_SIZE -p $PORT 

