#!/bin/bash

. ${DAQROOT}/runthedaq/daq_opts

if [ -e "${ETSYSPIDFILE}" ]; then
	id_et_sys=`cat ${ETSYSPIDFILE}`
	if [ `ps -p ${id_et_sys} | grep xterm | wc -l` -eq 1 ]; then 
		echo "Killing ET system process with pid $id_et_sys"
		kill ${id_et_sys}
		if [ `ps -p ${id_et_sys} | grep xterm | wc -l` -eq 1 ]; then
			echo "Original kill of ET unsuccessful!"
			echo "Trying kill -9."
			kill -9 ${id_et_sys}
		fi
		echo "Removing ${ETSYSPIDFILE}"
		rm ${ETSYSPIDFILE}
	else
		echo "ET does not seem to be running with pid ${id_et_sys}"
	fi
else
	echo "${ETSYSPIDFILE} does not exist. Assume no process is running."
fi


if [ -e "${ETMONPIDFILE}" ]; then
	id_et_mon=`cat ${ETMONPIDFILE}`
	if [ `ps -p ${id_et_mon} | grep xterm | wc -l` -eq 1 ]; then 
		echo "Killing ET monitor process with pid $id_et_mon"
		kill ${id_et_mon}
		if [ `ps -p ${id_et_mon} | grep xterm | wc -l` -eq 1 ]; then
			echo "Original kill of the monitor unsuccessful!"
			echo "Trying kill -9."
			kill -9 ${id_et_mon}
		fi
		echo "Removing ${ETMONPIDFILE}"
		rm ${ETMONPIDFILE}
	else
		echo "ET does not seem to be running with pid ${id_et_mon}"
	fi
else
	echo "${ETMONPIDFILE} does not exist. Assume no process is running."
fi


if [ -e "${EBSRVPIDFILE}" ]; then
	id_eb_srv=`cat ${EBSRVPIDFILE}`
	if [ `ps -p ${id_eb_srv} | grep xterm | wc -l` -eq 1 ]; then 
		echo "Killing EB service process with pid $id_eb_srv"
		kill ${id_eb_srv}
		if [ `ps -p ${id_eb_srv} | grep xterm | wc -l` -eq 1 ]; then
			echo "Original kill of EB service unsuccessful!"
			echo "Trying kill -9."
			kill -9 ${id_et_srv}
		fi
		echo "Removing ${EBSRVPIDFILE}"
		rm ${EBSRVPIDFILE}
	else
		echo "EB does not seem to be running with pid ${id_eb_srv}"
	fi
else
	echo "${EBSRVPIDFILE} does not exist. Assume no process is running."
fi

