#!/bin/bash

# Argument List:
#  $1 == et_system file name
if [ $# -ne 1 ]; then
	echo Please supply et_system file name.
	exit 1
fi

source $DAQROOT/setup_daqbuild.sh

if [ "$LOCALE" == "" ]
then
	echo No LOCALE defined!  Please source setup_daqbuild.sh!
	exit 1
fi

if [ $LOCALE == 'FNAL' ]
then
	$ET_HOME/Linux-x86_64-64/bin/et_monitor -f $1 
fi

