#!/bin/bash

# Argument List:
#  $1 == et_system file name
if [ $# -ne 1 ]; then
	echo Please supply et_system file name.
	exit 1
fi

if [ "$LOCALE" == "" ]
then
	echo No LOCALE defined!  It is impossible to configure the MINERvA DAQ Environment!
	exit 1
fi

if [ "$ET_HOME" == "" ]
then
        echo No ET_HOME defined!  Please configure your environment!
        exit 1
fi

#source /work/software/mnvonline/mnvdaq/setup_daqbuild.sh
$ET_HOME/Linux-x86_64-64/bin/et_monitor -f $1 

