#!/bin/bash

# Argument List:
#  $1 == et_system file name
if [ $# -ne 2 ]; then
	echo Please supply et_system file name and output file name.
	exit 1
fi

ETSYS=$1
OUTFL=$2

if [ "$LOCALE" == "" ]
then
	echo No LOCALE defined!  It is impossible to configure the MINERvA DAQ Environment!
	exit 1
fi

if [ "$DAQROOT" == "" ]
then
	echo No DAQROOT defined!  Please configure your environment!
	exit 1
fi

# We pass both the system name and output file - must contain the full path! 
nice ${DAQROOT}/bin/event_builder $ETSYS $OUTFL 
