#!/bin/bash

# Running Modes:
#  0 == OneShot
#  1 == NuMI
# See the DAQ code for more... 

ETNAME=testme
NFEBS=4
NGATES=10
RUNMODE=0
RUN=1337
SUB=391

while [ $# -gt 0 ]
do
	case $1 in
		-et)	ETNAME=$2
			shift 2 
           		;;
		-f)	NFEBS=$2
			shift 2
			;;
		-g)	NGATES=$2
			shift 2
			;;
		-m)	RUNMODE=$2
			shift 2
			;;
		-r)	RUN=$2
			shift 2
			;;
		-s)	SUB=$2
			shift 2
			;;
	esac
done


xterm -hold -geometry 80x30+380+1 -sl 1000 -e ./start_et_system $ETNAME $NFEBS $NGATES &
export ET_SYST_TERM_PID=$!
echo ET_SYST_TERM_PID=${ET_SYST_TERM_PID}
sleep 2s

xterm -hold -geometry 88x60+890+1 -sl 1000 -e ./start_et_monitor $ETNAME &
export ET_MON_TERM_PID=$!
echo ET_MON_TERM_PID=${ET_MON_TERM_PID}
sleep 2s

xterm -hold -geometry 80x28+380+421 -sl 10000 -e ./start_eb_service $ETNAME &
export EB_SERV_TERM_PID=$!
echo EB_SERV_TERM_PID=${EB_SERV_TERM_PID}
sleep 16s

valgrind -v --log-file-exactly=val_minervadaq.txt ${DAQROOT}/bin/minervadaq -et $ETNAME -g $NGATES -m $RUNMODE -r $RUN -s $SUB &

