#!/bin/bash

# Argument List:
#  $1 == et_system file name
if [ $# -ne 1 ]; then
	echo Please supply et_system file name.
	exit 1
fi

if [ "$LOCALE" == "" ]
then
	echo No LOCALE defined!  It is impossible to configure the MINERvA DAQ Environment!
	exit 1
fi

if [ $LOCALE == 'FNAL' ]
then
	source /work/software/mnvsingle/mnvdaq/single_daqbuild.sh
	nice ${DAQROOT}/bin/event_builder $1  
fi

