#!/bin/bash

Help()
{
	echo  "Usage : start_daq_singleton -et <ET filename (stub)> -f <Num FEBS> -g <Num Gates> -m <Mode> -r <Run Num> -s <Sub Num>"
	echo  "          -t <n seconds (not supported)> -d <detector code (see DAQHeader class)> -cf <slow control config file>"
}

if [ $# -eq 0 ]
then
	Help
	exit 1
fi

# Running Modes:
#  0 == OneShot
#  1 == NuMI
# See the DAQ code for more... 

. ${DAQROOT}/runthedaq/daq_opts

FILEROOT=testme
NFEBS=4
NGATES=10
RUNMODE=0
RUN=1337
SUB=391
NSECONDS=0  # NSECONDS is a dummy argument for the DAQ right now.
DETECTOR=0  # See Event/MinervaEvent/DAQHeader.xml for the detector codes.
CONFIGFILE=unknown # This is the filename for the config loaded by the slow control.

while [ $# -gt 0 ]
do
	case $1 in
		-et)	FILEROOT=$2
			shift 2 
           		;;
		-f)	NFEBS=$2
			shift 2
			;;
		-g)	NGATES=$2
			shift 2
			;;
		-m)	RUNMODE=$2
			shift 2
			;;
		-r)	RUN=$2
			shift 2
			;;
		-s)	SUB=$2
			shift 2
			;;
		-t)	NSECONDS=$2
			shift 2
			;;
		-d)	DETECTOR=$2
			shift 2
			;;
		-cf)	CONFIGFILE=$2
			shift 2
			;;
	esac
done

ETSYS=/work/data/etsys/$FILEROOT
OUTFL=/work/data/rawdata/$FILEROOT.dat

xterm -geometry 80x30+380+1 -sl 1000 -e ./start_et_system $ETSYS $NFEBS $NGATES &
export ET_SYST_TERM_PID=$!
echo ET_SYST_TERM_PID=${ET_SYST_TERM_PID}
echo $ET_SYST_TERM_PID > $ETSYSPIDFILE 
sleep 2s

xterm -geometry 88x60+890+1 -sl 1000 -e ./start_et_monitor $ETSYS &
export ET_MON_TERM_PID=$!
echo ET_MON_TERM_PID=${ET_MON_TERM_PID}
echo $ET_MON_TERM_PID > $ETMONPIDFILE 
sleep 2s

xterm -geometry 80x28+380+421 -sl 10000 -e ./start_eb_service $ETSYS $OUTFL &
export EB_SERV_TERM_PID=$!
echo EB_SERV_TERM_PID=${EB_SERV_TERM_PID}
echo $EB_SERV_TERM_PID > $EBSRVPIDFILE 
sleep 15s

# Note we do not pass the full path of the ET system to the daq.
# That information is attached within the process itself.
${DAQROOT}/bin/minervadaq -et $FILEROOT -g $NGATES -m $RUNMODE -r $RUN -s $SUB -d $DETECTOR -t $NSECONDS -cf $CONFIGFILE &

