#!/bin/bash

# Argument List:
#  $1 == et_system file name
#  $2 == number of gates to process
#if [ $# -ne 2 ]; then
#	echo Please supply et_system file name and number of gates.
#	exit 1
#fi

if [ $# -ne 1 ]; then
        echo Please supply et_system file name.
        exit 1
fi


xterm -hold -geometry 80x30 -sl 1000 -e ./start_et_system $1 1000 &
export ET_SYST_TERM_PID=$!
echo ET_SYST_TERM_PID=${ET_SYST_TERM_PID}
sleep 2s

xterm -hold -geometry 90x40 -sl 1000 -e ./start_et_monitor $1 &
export ET_MON_TERM_PID=$!
echo ET_MON_TERM_PID=${ET_MON_TERM_PID}
sleep 2s

xterm -hold -geometry 80x60 -sl 10000 -e ./start_eb_service $1 &
export EB_SERV_TERM_PID=$!
echo EB_SERV_TERM_PID=${EB_SERV_TERM_PID}
sleep 28s

nice ${DAQROOT}/bin/daq_master $1 1 &
