#!/bin/bash

# Argument List:
#  $1 == et_system file name
if [ $# -ne 1 ]; then
	echo Please supply et_system file name.
	exit 1
fi

if [ "$LOCALE" == "" ]
then
	echo No LOCALE defined!  It is impossible to configure the MINERvA DAQ Environment!
	exit 1
fi

if [ "$DAQROOT" == "" ]
then
	echo No DAQROOT defined!  Please configure your environment!
	exit 1
fi

#source /work/software/mnvonline/mnvdaq/setup_daqbuild.sh
nice ${DAQROOT}/bin/event_builder $1  
